version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=anoyne@anywhere.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - 31006:80

  jupyter:
    image: jupyter/tensorflow-notebook
    restart: always
    ports:
      - 31002:8888
      - 31100:9990
      - 31101:9991
      - 31102:9992
      - 31103:9993
    volumes:
      - ./notebooks:/home/jovyan/work

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 31004:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
       - mongo

  couch:
    image: apache/couchdb
    restart: always
    ports:
      - 31005:5984 
    environment:
      COUCHDB_USER: root
      COUCHDB_PASSWORD: example

  nginx:
    build:
      context: ./nginx
    ports:
      - 50000:80
    depends_on:
      - jupyter
